# Generated by Django 4.0.3 on 2022-05-28 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='clientlevel',
            field=models.CharField(choices=[('R', 'Red'), ('G', 'Green'), ('B', 'Blue')], default='B', max_length=1),
        ),
        migrations.DeleteModel(
            name='Client_level',
        ),
    ]
