# Generated by Django 4.0.3 on 2022-05-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treeApp', '0002_alter_clients_clientlevel_delete_client_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
