# Generated by Django 4.0.3 on 2022-05-28 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treeApp', '0004_alter_clients_id_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('order_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('recived_date', models.DateField()),
                ('delivery_date', models.DateField()),
                ('design_types', models.CharField(choices=[('A', 'Attached Design'), ('O', 'Office Design')], max_length=1)),
                ('design_path', models.CharField(max_length=255, null=True)),
                ('design_category', models.CharField(max_length=255, null=True)),
                ('printing_type', models.CharField(max_length=255, null=True)),
                ('materials', models.CharField(max_length=255, null=True)),
                ('color', models.CharField(max_length=255, null=True)),
                ('thickness', models.FloatField(null=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treeApp.clients')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treeApp.users')),
            ],
        ),
    ]
