# Generated by Django 4.0.3 on 2022-05-28 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treeApp', '0005_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='Post_print_services',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='orders',
            name='size_high',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='size_width',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='design_category',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='orders',
            name='printing_type',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
