# Generated by Django 4.0.3 on 2022-05-28 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treeApp', '0006_orders_post_print_services_orders_size_high_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='design_category',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
