# Generated by Django 4.0.3 on 2022-05-28 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treeApp', '0007_alter_orders_design_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='design_category',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
