# Generated by Django 4.0.3 on 2022-05-28 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treeApp', '0008_alter_orders_design_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='state',
            field=models.CharField(choices=[('D', 'Ideal'), ('I', 'in Progress'), ('F', 'Finished')], default='D', max_length=1),
        ),
    ]
