# Generated by Django 4.0.3 on 2022-05-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treeApp', '0009_orders_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='phone_number',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
