# Generated by Django 4.0.3 on 2022-05-31 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treeApp', '0010_alter_clients_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='notes',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='orders',
            name='notes',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
