# Generated by Django 4.0.3 on 2022-05-31 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treeApp', '0018_alter_clients_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='delivery_date',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='orders',
            name='recived_date',
            field=models.CharField(max_length=255),
        ),
    ]
