# Generated by Django 4.0.3 on 2022-05-31 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treeApp', '0019_alter_orders_delivery_date_alter_orders_recived_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='delivery_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='recived_date',
            field=models.DateField(),
        ),
    ]
